import type { Metadata } from "next"
import { Poppins } from 'next/font/google'
import "./globals.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import logo  from "@/components/assets/logo.jpg"
import TransitionEffect from "@/components/TransitionEffect"
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Shova Bhagwati",
  description: "Generated by Ghost",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={logo.src} />
      </head>
      <body className={`${poppins.className} antialiased min-h-screen flex flex-col`}>
          <TransitionEffect />
        <Navbar />
        <main className="flex-1 mx-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}

